//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("READBModel", "FK__tblAssign__user___0AD2A005", "tblUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(READBModel.tblUsers), "tblAssignmentDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(READBModel.tblAssignmentDetails), true)]
[assembly: EdmRelationshipAttribute("READBModel", "FK__tblAssignm__a_id__09DE7BCC", "tblAssignments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(READBModel.tblAssignments), "tblAssignmentDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(READBModel.tblAssignmentDetails), true)]
[assembly: EdmRelationshipAttribute("READBModel", "FK__tblAssign__user___0519C6AF", "tblUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(READBModel.tblUsers), "tblAssignments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(READBModel.tblAssignments), true)]
[assembly: EdmRelationshipAttribute("READBModel", "FK__tblQuerie__user___0F975522", "tblUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(READBModel.tblUsers), "tblQueries", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(READBModel.tblQueries), true)]

#endregion

namespace READBModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class READBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new READBEntities object using the connection string found in the 'READBEntities' section of the application configuration file.
        /// </summary>
        public READBEntities() : base("name=READBEntities", "READBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new READBEntities object.
        /// </summary>
        public READBEntities(string connectionString) : base(connectionString, "READBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new READBEntities object.
        /// </summary>
        public READBEntities(EntityConnection connection) : base(connection, "READBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAssignmentDetails> tblAssignmentDetails
        {
            get
            {
                if ((_tblAssignmentDetails == null))
                {
                    _tblAssignmentDetails = base.CreateObjectSet<tblAssignmentDetails>("tblAssignmentDetails");
                }
                return _tblAssignmentDetails;
            }
        }
        private ObjectSet<tblAssignmentDetails> _tblAssignmentDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAssignments> tblAssignments
        {
            get
            {
                if ((_tblAssignments == null))
                {
                    _tblAssignments = base.CreateObjectSet<tblAssignments>("tblAssignments");
                }
                return _tblAssignments;
            }
        }
        private ObjectSet<tblAssignments> _tblAssignments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFaqs> tblFaqs
        {
            get
            {
                if ((_tblFaqs == null))
                {
                    _tblFaqs = base.CreateObjectSet<tblFaqs>("tblFaqs");
                }
                return _tblFaqs;
            }
        }
        private ObjectSet<tblFaqs> _tblFaqs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblQueries> tblQueries
        {
            get
            {
                if ((_tblQueries == null))
                {
                    _tblQueries = base.CreateObjectSet<tblQueries>("tblQueries");
                }
                return _tblQueries;
            }
        }
        private ObjectSet<tblQueries> _tblQueries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUsers> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUsers>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUsers> _tblUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAssignmentDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAssignmentDetails(tblAssignmentDetails tblAssignmentDetails)
        {
            base.AddObject("tblAssignmentDetails", tblAssignmentDetails);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAssignments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAssignments(tblAssignments tblAssignments)
        {
            base.AddObject("tblAssignments", tblAssignments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFaqs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFaqs(tblFaqs tblFaqs)
        {
            base.AddObject("tblFaqs", tblFaqs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblQueries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblQueries(tblQueries tblQueries)
        {
            base.AddObject("tblQueries", tblQueries);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUsers tblUsers)
        {
            base.AddObject("tblUsers", tblUsers);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="READBModel", Name="tblAssignmentDetails")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAssignmentDetails : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAssignmentDetails object.
        /// </summary>
        /// <param name="ad_id">Initial value of the ad_id property.</param>
        public static tblAssignmentDetails CreatetblAssignmentDetails(global::System.Int64 ad_id)
        {
            tblAssignmentDetails tblAssignmentDetails = new tblAssignmentDetails();
            tblAssignmentDetails.ad_id = ad_id;
            return tblAssignmentDetails;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ad_id
        {
            get
            {
                return _ad_id;
            }
            set
            {
                if (_ad_id != value)
                {
                    Onad_idChanging(value);
                    ReportPropertyChanging("ad_id");
                    _ad_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ad_id");
                    Onad_idChanged();
                }
            }
        }
        private global::System.Int64 _ad_id;
        partial void Onad_idChanging(global::System.Int64 value);
        partial void Onad_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> a_id
        {
            get
            {
                return _a_id;
            }
            set
            {
                Ona_idChanging(value);
                ReportPropertyChanging("a_id");
                _a_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("a_id");
                Ona_idChanged();
            }
        }
        private Nullable<global::System.Int64> _a_id;
        partial void Ona_idChanging(Nullable<global::System.Int64> value);
        partial void Ona_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int64> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int64> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String student_roll_no
        {
            get
            {
                return _student_roll_no;
            }
            set
            {
                Onstudent_roll_noChanging(value);
                ReportPropertyChanging("student_roll_no");
                _student_roll_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("student_roll_no");
                Onstudent_roll_noChanged();
            }
        }
        private global::System.String _student_roll_no;
        partial void Onstudent_roll_noChanging(global::System.String value);
        partial void Onstudent_roll_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_file_name
        {
            get
            {
                return _a_file_name;
            }
            set
            {
                Ona_file_nameChanging(value);
                ReportPropertyChanging("a_file_name");
                _a_file_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("a_file_name");
                Ona_file_nameChanged();
            }
        }
        private global::System.String _a_file_name;
        partial void Ona_file_nameChanging(global::System.String value);
        partial void Ona_file_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ad_uploaded_date
        {
            get
            {
                return _ad_uploaded_date;
            }
            set
            {
                Onad_uploaded_dateChanging(value);
                ReportPropertyChanging("ad_uploaded_date");
                _ad_uploaded_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ad_uploaded_date");
                Onad_uploaded_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ad_uploaded_date;
        partial void Onad_uploaded_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onad_uploaded_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ad_marks
        {
            get
            {
                return _ad_marks;
            }
            set
            {
                Onad_marksChanging(value);
                ReportPropertyChanging("ad_marks");
                _ad_marks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ad_marks");
                Onad_marksChanged();
            }
        }
        private Nullable<global::System.Decimal> _ad_marks;
        partial void Onad_marksChanging(Nullable<global::System.Decimal> value);
        partial void Onad_marksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblAssign__user___0AD2A005", "tblUsers")]
        public tblUsers tblUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0AD2A005", "tblUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0AD2A005", "tblUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUsers> tblUsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0AD2A005", "tblUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0AD2A005", "tblUsers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblAssignm__a_id__09DE7BCC", "tblAssignments")]
        public tblAssignments tblAssignments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssignments>("READBModel.FK__tblAssignm__a_id__09DE7BCC", "tblAssignments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssignments>("READBModel.FK__tblAssignm__a_id__09DE7BCC", "tblAssignments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblAssignments> tblAssignmentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssignments>("READBModel.FK__tblAssignm__a_id__09DE7BCC", "tblAssignments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblAssignments>("READBModel.FK__tblAssignm__a_id__09DE7BCC", "tblAssignments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="READBModel", Name="tblAssignments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAssignments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAssignments object.
        /// </summary>
        /// <param name="a_id">Initial value of the a_id property.</param>
        public static tblAssignments CreatetblAssignments(global::System.Int64 a_id)
        {
            tblAssignments tblAssignments = new tblAssignments();
            tblAssignments.a_id = a_id;
            return tblAssignments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 a_id
        {
            get
            {
                return _a_id;
            }
            set
            {
                if (_a_id != value)
                {
                    Ona_idChanging(value);
                    ReportPropertyChanging("a_id");
                    _a_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("a_id");
                    Ona_idChanged();
                }
            }
        }
        private global::System.Int64 _a_id;
        partial void Ona_idChanging(global::System.Int64 value);
        partial void Ona_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_name
        {
            get
            {
                return _a_name;
            }
            set
            {
                Ona_nameChanging(value);
                ReportPropertyChanging("a_name");
                _a_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("a_name");
                Ona_nameChanged();
            }
        }
        private global::System.String _a_name;
        partial void Ona_nameChanging(global::System.String value);
        partial void Ona_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_description
        {
            get
            {
                return _a_description;
            }
            set
            {
                Ona_descriptionChanging(value);
                ReportPropertyChanging("a_description");
                _a_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("a_description");
                Ona_descriptionChanged();
            }
        }
        private global::System.String _a_description;
        partial void Ona_descriptionChanging(global::System.String value);
        partial void Ona_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_file_name
        {
            get
            {
                return _a_file_name;
            }
            set
            {
                Ona_file_nameChanging(value);
                ReportPropertyChanging("a_file_name");
                _a_file_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("a_file_name");
                Ona_file_nameChanged();
            }
        }
        private global::System.String _a_file_name;
        partial void Ona_file_nameChanging(global::System.String value);
        partial void Ona_file_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course_name
        {
            get
            {
                return _course_name;
            }
            set
            {
                Oncourse_nameChanging(value);
                ReportPropertyChanging("course_name");
                _course_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_name");
                Oncourse_nameChanged();
            }
        }
        private global::System.String _course_name;
        partial void Oncourse_nameChanging(global::System.String value);
        partial void Oncourse_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String batch_no
        {
            get
            {
                return _batch_no;
            }
            set
            {
                Onbatch_noChanging(value);
                ReportPropertyChanging("batch_no");
                _batch_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("batch_no");
                Onbatch_noChanged();
            }
        }
        private global::System.String _batch_no;
        partial void Onbatch_noChanging(global::System.String value);
        partial void Onbatch_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course_year
        {
            get
            {
                return _course_year;
            }
            set
            {
                Oncourse_yearChanging(value);
                ReportPropertyChanging("course_year");
                _course_year = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_year");
                Oncourse_yearChanged();
            }
        }
        private global::System.String _course_year;
        partial void Oncourse_yearChanging(global::System.String value);
        partial void Oncourse_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course_semester
        {
            get
            {
                return _course_semester;
            }
            set
            {
                Oncourse_semesterChanging(value);
                ReportPropertyChanging("course_semester");
                _course_semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_semester");
                Oncourse_semesterChanged();
            }
        }
        private global::System.String _course_semester;
        partial void Oncourse_semesterChanging(global::System.String value);
        partial void Oncourse_semesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String a_assigned_by
        {
            get
            {
                return _a_assigned_by;
            }
            set
            {
                Ona_assigned_byChanging(value);
                ReportPropertyChanging("a_assigned_by");
                _a_assigned_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("a_assigned_by");
                Ona_assigned_byChanged();
            }
        }
        private global::System.String _a_assigned_by;
        partial void Ona_assigned_byChanging(global::System.String value);
        partial void Ona_assigned_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int64> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int64> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> a_assigned_date
        {
            get
            {
                return _a_assigned_date;
            }
            set
            {
                Ona_assigned_dateChanging(value);
                ReportPropertyChanging("a_assigned_date");
                _a_assigned_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("a_assigned_date");
                Ona_assigned_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _a_assigned_date;
        partial void Ona_assigned_dateChanging(Nullable<global::System.DateTime> value);
        partial void Ona_assigned_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> a_submit_date
        {
            get
            {
                return _a_submit_date;
            }
            set
            {
                Ona_submit_dateChanging(value);
                ReportPropertyChanging("a_submit_date");
                _a_submit_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("a_submit_date");
                Ona_submit_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _a_submit_date;
        partial void Ona_submit_dateChanging(Nullable<global::System.DateTime> value);
        partial void Ona_submit_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblAssignm__a_id__09DE7BCC", "tblAssignmentDetails")]
        public EntityCollection<tblAssignmentDetails> tblAssignmentDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblAssignmentDetails>("READBModel.FK__tblAssignm__a_id__09DE7BCC", "tblAssignmentDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblAssignmentDetails>("READBModel.FK__tblAssignm__a_id__09DE7BCC", "tblAssignmentDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblAssign__user___0519C6AF", "tblUsers")]
        public tblUsers tblUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0519C6AF", "tblUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0519C6AF", "tblUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUsers> tblUsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0519C6AF", "tblUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUsers>("READBModel.FK__tblAssign__user___0519C6AF", "tblUsers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="READBModel", Name="tblFaqs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFaqs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFaqs object.
        /// </summary>
        /// <param name="f_id">Initial value of the f_id property.</param>
        public static tblFaqs CreatetblFaqs(global::System.Int32 f_id)
        {
            tblFaqs tblFaqs = new tblFaqs();
            tblFaqs.f_id = f_id;
            return tblFaqs;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 f_id
        {
            get
            {
                return _f_id;
            }
            set
            {
                if (_f_id != value)
                {
                    Onf_idChanging(value);
                    ReportPropertyChanging("f_id");
                    _f_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("f_id");
                    Onf_idChanged();
                }
            }
        }
        private global::System.Int32 _f_id;
        partial void Onf_idChanging(global::System.Int32 value);
        partial void Onf_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> f_parent_id
        {
            get
            {
                return _f_parent_id;
            }
            set
            {
                Onf_parent_idChanging(value);
                ReportPropertyChanging("f_parent_id");
                _f_parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("f_parent_id");
                Onf_parent_idChanged();
            }
        }
        private Nullable<global::System.Int32> _f_parent_id;
        partial void Onf_parent_idChanging(Nullable<global::System.Int32> value);
        partial void Onf_parent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String f_description
        {
            get
            {
                return _f_description;
            }
            set
            {
                Onf_descriptionChanging(value);
                ReportPropertyChanging("f_description");
                _f_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("f_description");
                Onf_descriptionChanged();
            }
        }
        private global::System.String _f_description;
        partial void Onf_descriptionChanging(global::System.String value);
        partial void Onf_descriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="READBModel", Name="tblQueries")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblQueries : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblQueries object.
        /// </summary>
        /// <param name="q_id">Initial value of the q_id property.</param>
        public static tblQueries CreatetblQueries(global::System.Int64 q_id)
        {
            tblQueries tblQueries = new tblQueries();
            tblQueries.q_id = q_id;
            return tblQueries;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 q_id
        {
            get
            {
                return _q_id;
            }
            set
            {
                if (_q_id != value)
                {
                    Onq_idChanging(value);
                    ReportPropertyChanging("q_id");
                    _q_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("q_id");
                    Onq_idChanged();
                }
            }
        }
        private global::System.Int64 _q_id;
        partial void Onq_idChanging(global::System.Int64 value);
        partial void Onq_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> q_parent_id
        {
            get
            {
                return _q_parent_id;
            }
            set
            {
                Onq_parent_idChanging(value);
                ReportPropertyChanging("q_parent_id");
                _q_parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q_parent_id");
                Onq_parent_idChanged();
            }
        }
        private Nullable<global::System.Int64> _q_parent_id;
        partial void Onq_parent_idChanging(Nullable<global::System.Int64> value);
        partial void Onq_parent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int64> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int64> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String q_description
        {
            get
            {
                return _q_description;
            }
            set
            {
                Onq_descriptionChanging(value);
                ReportPropertyChanging("q_description");
                _q_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("q_description");
                Onq_descriptionChanged();
            }
        }
        private global::System.String _q_description;
        partial void Onq_descriptionChanging(global::System.String value);
        partial void Onq_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> q_date
        {
            get
            {
                return _q_date;
            }
            set
            {
                Onq_dateChanging(value);
                ReportPropertyChanging("q_date");
                _q_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q_date");
                Onq_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _q_date;
        partial void Onq_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onq_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblQuerie__user___0F975522", "tblUsers")]
        public tblUsers tblUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblQuerie__user___0F975522", "tblUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblQuerie__user___0F975522", "tblUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUsers> tblUsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUsers>("READBModel.FK__tblQuerie__user___0F975522", "tblUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUsers>("READBModel.FK__tblQuerie__user___0F975522", "tblUsers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="READBModel", Name="tblUsers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUsers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUsers object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static tblUsers CreatetblUsers(global::System.Int64 user_id)
        {
            tblUsers tblUsers = new tblUsers();
            tblUsers.user_id = user_id;
            return tblUsers;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int64 _user_id;
        partial void Onuser_idChanging(global::System.Int64 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_type
        {
            get
            {
                return _user_type;
            }
            set
            {
                Onuser_typeChanging(value);
                ReportPropertyChanging("user_type");
                _user_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_type");
                Onuser_typeChanged();
            }
        }
        private global::System.String _user_type;
        partial void Onuser_typeChanging(global::System.String value);
        partial void Onuser_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course_name
        {
            get
            {
                return _course_name;
            }
            set
            {
                Oncourse_nameChanging(value);
                ReportPropertyChanging("course_name");
                _course_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_name");
                Oncourse_nameChanged();
            }
        }
        private global::System.String _course_name;
        partial void Oncourse_nameChanging(global::System.String value);
        partial void Oncourse_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String batch_no
        {
            get
            {
                return _batch_no;
            }
            set
            {
                Onbatch_noChanging(value);
                ReportPropertyChanging("batch_no");
                _batch_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("batch_no");
                Onbatch_noChanged();
            }
        }
        private global::System.String _batch_no;
        partial void Onbatch_noChanging(global::System.String value);
        partial void Onbatch_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course_year
        {
            get
            {
                return _course_year;
            }
            set
            {
                Oncourse_yearChanging(value);
                ReportPropertyChanging("course_year");
                _course_year = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_year");
                Oncourse_yearChanged();
            }
        }
        private global::System.String _course_year;
        partial void Oncourse_yearChanging(global::System.String value);
        partial void Oncourse_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course_semester
        {
            get
            {
                return _course_semester;
            }
            set
            {
                Oncourse_semesterChanging(value);
                ReportPropertyChanging("course_semester");
                _course_semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("course_semester");
                Oncourse_semesterChanged();
            }
        }
        private global::System.String _course_semester;
        partial void Oncourse_semesterChanging(global::System.String value);
        partial void Oncourse_semesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String student_roll_no
        {
            get
            {
                return _student_roll_no;
            }
            set
            {
                Onstudent_roll_noChanging(value);
                ReportPropertyChanging("student_roll_no");
                _student_roll_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("student_roll_no");
                Onstudent_roll_noChanged();
            }
        }
        private global::System.String _student_roll_no;
        partial void Onstudent_roll_noChanging(global::System.String value);
        partial void Onstudent_roll_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_password
        {
            get
            {
                return _user_password;
            }
            set
            {
                Onuser_passwordChanging(value);
                ReportPropertyChanging("user_password");
                _user_password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_password");
                Onuser_passwordChanged();
            }
        }
        private global::System.String _user_password;
        partial void Onuser_passwordChanging(global::System.String value);
        partial void Onuser_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_status
        {
            get
            {
                return _user_status;
            }
            set
            {
                Onuser_statusChanging(value);
                ReportPropertyChanging("user_status");
                _user_status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_status");
                Onuser_statusChanged();
            }
        }
        private global::System.String _user_status;
        partial void Onuser_statusChanging(global::System.String value);
        partial void Onuser_statusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblAssign__user___0AD2A005", "tblAssignmentDetails")]
        public EntityCollection<tblAssignmentDetails> tblAssignmentDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblAssignmentDetails>("READBModel.FK__tblAssign__user___0AD2A005", "tblAssignmentDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblAssignmentDetails>("READBModel.FK__tblAssign__user___0AD2A005", "tblAssignmentDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblAssign__user___0519C6AF", "tblAssignments")]
        public EntityCollection<tblAssignments> tblAssignments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblAssignments>("READBModel.FK__tblAssign__user___0519C6AF", "tblAssignments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblAssignments>("READBModel.FK__tblAssign__user___0519C6AF", "tblAssignments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("READBModel", "FK__tblQuerie__user___0F975522", "tblQueries")]
        public EntityCollection<tblQueries> tblQueries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblQueries>("READBModel.FK__tblQuerie__user___0F975522", "tblQueries");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblQueries>("READBModel.FK__tblQuerie__user___0F975522", "tblQueries", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
